#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - network
  source:
    id: ubuntucinnamon-desktop-minimal
  locale: de_DE.UTF-8
  refresh-installer:
    update: true
  keyboard:
    layout: de
  timezone: Europe/Berlin
  identity:
    hostname: kulturloge-dd-notebook
  user-data:
    users:
      - name: kulturloge-dd
        passwd: $6$F/FsvYjDVVMFmVzg$DnL9AD0XoYf8mAyjCLVYzytV0V/RTK8d8x4jCxhq4/ndqXuX8n7cvL3WbEoIAxSnedERFtRc9yV5GNZl7PAFx0
        groups: users
      - name: admin
        passwd: $6$UxcEr4UTrb86Zimr$mNbTTIaP8OORl5i3eFHgy04DYZ5zLYiRAZyKkV22uskhTenfjS13mnEfgmaomq6lNj9eiHpgtAZNyaBZiC6yo0
        groups: adm,sudo
  ssh:
    install-server: false  
  packages:
    - firefox
    - firefox-locale-de
    - libreoffice
    - libreoffice-l10n-de
    - network-manager
  updates: all
  shutdown: reboot
  storage:
    layout:
      name: direct
